### ISSUE TITLE
Add the ability to auto assign runner roles on schedule release

### ISSUE THREAD

**Issue by nicnacnic** [oengusio/oengus-discord-bot#2]
This would be super useful for larger marathons. Specify a marathon and a role, and if the user's run was accepted and they are in the discord, give them the role. Also have the ability to reverse this (remove runner roles instead of add).

**Comment by duncte123** [comment]
This feature will be tested during ESA winter 2023. If all tests are successful this will be released to the public together with a new settings tab for marathons in the front-ed
